docker-build:
  # Official docker image.
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE"
  variables:
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_TLS_CERTDIR: ""
  only:
    - master

deploy-master:
  stage: deploy
  image: bitnami/kubectl
  script:
    - kubectl get deployment hola-mundo || kubectl create deployment hola-mundo --image="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
    - kubectl set image deployment/hola-mundo hola-mundo="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
  only:
    - master
